export const Constants = {
    MOTIVATIONS_STORAGE_KEY: 'motivations',
    CATEGORIES_STORAGE_KEY: 'categories',
    AFFIRMATION: 'affirmation',
    LONELINESS: 'loneliness',
    LOVE: 'love',
    MOTIVATION: 'motivation',
    QUOTES: 'quotes',
    SMALL_ICON_SIZE: 20,
    MEDIUM_ICON_SIZE: 25,
    BIG_ICON_SIZE: 30,
    BIGGER_ICON_SIZE: 32,
    BIGGEST_ICON_SIZE: 40,
    ANTDESIGN_ICON: 'antDesign',
    ENTYPO_ICON: 'entypo',
    EVILICONS_ICON: 'evilIcons',
    FEATHER_ICON: 'feather',
    FONTAWESOME_ICON: 'fontAwesome',
    FONTAWESOME5_ICON: 'fontAwesome5',
    FONTISTO_ICON: 'fontisto',
    FOUNDATION_ICON: 'foundation',
    IONICONS_ICON: 'ionIcons',
    MATERIALCOMMUNITYICONS_ICON: 'materialCommunityIcons',
    MATERIALICONS_ICON: 'materialIcons',
    OCTICONS_ICON: 'octIcons',
    SIMPLELINESICONS_ICON: 'simpleLineIcons',
    ZOCIAL_ICON: 'zocial',
};
