export const Constants = {
    MOTIVATIONS_STORAGE_KEY: 'motivations',
    CATEGORIES_STORAGE_KEY: 'categories',
    AFFIRMATION: 'affirmation',
    LONELINESS: 'loneliness',
    LOVE: 'love',
    MOTIVATION: 'motivation',
    QUOTES: 'quotes',
    SMALL_ICON_SIZE: 20,
    MEDIUM_ICON_SIZE: 25,
    BIG_ICON_SIZE: 30,
    BIGGER_ICON_SIZE: 32,
    BIGGEST_ICON_SIZE: 40,
    ANTDESIGN_ICON: 'antDesign',
    ENTYPO_ICON: 'entypo',
    EVILICONS_ICON: 'evilIcons',
    FEATHER_ICON: 'feather',
    FONTAWESOME_ICON: 'fontAwesome',
    FONTAWESOME5_ICON: 'fontAwesome5',
    FONTISTO_ICON: 'fontisto',
    FOUNDATION_ICON: 'foundation',
    IONICONS_ICON: 'ionIcons',
    MATERIALCOMMUNITYICONS_ICON: 'materialCommunityIcons',
    MATERIALICONS_ICON: 'materialIcons',
    OCTICONS_ICON: 'octIcons',
    SIMPLELINESICONS_ICON: 'simpleLineIcons',
    ZOCIAL_ICON: 'zocial',
    CATEGORY_1: {
        id: 'category-1',
        category: 'Category 1',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
    CATEGORY_2: {
        id: 'category-2',
        category: 'Category 2',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
    CATEGORY_3: {
        id: 'category-3',
        category: 'Category 3',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
    CATEGORY_4: {
        id: 'category-4',
        category: 'Category 4',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
    CATEGORY_5: {
        id: 'category-5',
        category: 'Category 5',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
    CATEGORY_6: {
        id: 'category-6',
        category: 'Category 6',
        image: { uri: 'asset:/backgrounds/0.jpg' },
        isVisible: true,
    },
};
